#!/usr/bin/env bash
#displays a list of currently running processes.
echo "-----------------------------------------------"
echo "List of Currently Running Processes (Hierarchy)"
echo "-----------------------------------------------"
ps auxf
echo "-----------------------------------------------"
