#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
# Set the path for the PID file
PID_FILE="/var/run/myscript.pid"

# Function to clean up and exit
cleanup_and_exit() {
    echo "Cleaning up and exiting..."
    rm -f "$PID_FILE"
    exit 0
}

# Trap signals and call the cleanup_and_exit function
trap 'cleanup_and_exit' SIGQUIT SIGTERM

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Trap signals and call the corresponding functions
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

# Display PID and write it to the PID file
echo "$$" > "$PID_FILE"

# Infinite loop displaying messages
while true; do
    echo "To infinity and beyond"
    sleep 2
done
