#!/usr/bin/env bash
#displays numbers from 1 to 100.
num=1
while [ $num -lt 101 ]
do
    if (( num % 15 == 0 ))
    then
	echo "FizzBuzz"
    elif (( num % 5 == 0 ))
    then
	echo "Fizz"
    elif (( num % 3 == 0 ))
    then
	echo "Buzz"
    else
	echo $num
    fi
    (( num++ ))
done
