#!/usr/bin/env bash
#displays "Holberton School" 10 times using while loop

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then
	echo "Hi"
    else
	echo "Best School"
    fi
    (( count++ ))
done
